DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS profile CASCADE;
DROP TABLE IF EXISTS doctor CASCADE;
DROP TABLE IF EXISTS hospital CASCADE;
DROP TABLE IF EXISTS guest CASCADE;
DROP TABLE IF EXISTS appointment CASCADE;
DROP TABLE IF EXISTS address CASCADE;
