name: Angular app

on:
  push:
    branches: [features]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: node-version: 19
      - name: build the angular app
        run: |
          npm ci
          npm run build
